### ISSUE TITLE
"Rate My App" option in app's About and impact on "Rate My App"

### ISSUE THREAD

**Issue by ltomuta** [microsoft/rate-my-app#2]
An app may chose to implement a "Rate My App" button in app's about, to give a chance to the user to voluntarily rate the app at any given time.

In that case, the RMA component should have a "stop counters" method to be called when that button is pressed since presumably a rating was done already so there is no reason to count anymore.

**Comment by hamishwillee** [comment]
Yes :-)

**Comment by ltomuta** [comment]
Implemented in WP8 XAML app. At component level the Review() method was added in FeedbackHelper to allow the triggered review to update the state of the RMA component.
