### ISSUE TITLE
Cannot add control

### ISSUE THREAD

**Issue by GoFightNguyen** [microsoft/rate-my-app#22]
I installed RateMyApp through NuGet in Visual Studio 2013 to a Windows Phone 8 project.  When I add the control, I start getting an exception about "Message not having a public get"

**Comment by ltomuta** [comment]
Can you share a sample project? Also, would it make a difference if you use version 1.0.2 vs 1.1.0 ?

**Comment by GoFightNguyen** [comment]
It is working fine now.
