### ISSUE TITLE
Can't localizate RateMyApp

### ISSUE THREAD

**Issue by valereds** [microsoft/rate-my-app#23]
Added LanguageOverride="it-IT" to my FeedbackOverlay in mainPage.xaml but it's always in English. I tried to localizate in other language(french,german) but it's the same.
Any ideas?

**Comment by ltomuta** [comment]
I just tried with the WP8 version of the demo app and the override worked.

Make sure that your app does support the language you are overriding the component to.

**Comment by valereds** [comment]
yes i know, it's very strange. If i go to the setting of my app it says that default language is Italian..so everything should be ok ?! really don't know why

**Comment by ltomuta** [comment]
Could it be that in your project you are using "Italian", culture "it", instead of "Italian (Italy)", culture "it-IT" ?

**Comment by valereds** [comment]
No, pretty sure it's Italian (Italy)

**Comment by valereds** [comment]
![cattura2](https://f.cloud.github.com/assets/6317344/1844843/31af4540-7558-11e3-9839-5cd8b7717edd.PNG)
![cattura1](https://f.cloud.github.com/assets/6317344/1844844/31ce8b94-7558-11e3-94bc-12af62829406.PNG)

**Comment by ltomuta** [comment]
That part looks good, how about your project's settings?

![clipboard001](https://f.cloud.github.com/assets/2544090/1844906/69a1668a-755e-11e3-9035-81056b9fdb09.png)
![clipboard002](https://f.cloud.github.com/assets/2544090/1844907/69a7ac98-755e-11e3-8761-53f55abf3a6a.png)

**Comment by valereds** [comment]
Yes....
![cattura4](https://f.cloud.github.com/assets/6317344/1845243/59d6a41a-757a-11e3-9eef-e1da37803431.PNG)
![cattura3](https://f.cloud.github.com/assets/6317344/1845244/59dc3470-757a-11e3-9880-e0db5d32905f.PNG)

**Comment by ltomuta** [comment]
No idea, except maybe that you should try to remove the other two Italian cultures selected in the 2nd image.

If you can reproduce this with a small project, or if you can share your current app, I could try to debug this...

Lucian

Sent from my Nokia Lumia 920 powered by Windows Phone 8

**Comment by valereds** [comment]
Removed, and nothing..still in english..I really don't know what I've to do.
I would share my app, this is my first app and Think you can debug it better then me,
Can I send my projet to your email? Prefer to not share free on the web.

**Comment by ltomuta** [comment]
Ok, send it over and I will have a look at it. You can find my email address listed at https://github.com/ltomuta

**Comment by valereds** [comment]
Finally i've done it...tried lot of configurations, and now it works! 
Itomuta don't need to debug my code, thank you !

**Comment by ltomuta** [comment]
Great news.

Sent from my Nokia Lumia 920 powered by Windows Phone 8

---

De la: Valeredmailto:notifications@github.com
Trimis: ‎05.‎01.‎2014 14:23
Către: nokia-developer/rate-my-appmailto:rate-my-app@noreply.github.com
Subiect: Re: [rate-my-app] Can't localizate RateMyApp (#23)

Finally i've done it...tried lot of configurations, and now it works!
Itomuta don't need to debug my code, thank you !

---
