### ISSUE TITLE
Example library for WPAppStudio type app

### ISSUE THREAD

**Issue by hamishwillee** [microsoft/rate-my-app#27]
WPAppStudio are growing in popularity, but it isn't immediately obvious how to integrate with this feature. Would be great to have an example that shows how to do it.

Discussion of this first appeared in comments of http://developer.nokia.com/Community/Wiki/Implement_%22Rate_My_App%22_in_under_60_seconds

**Comment by ltomuta** [comment]
Very good idea. I will try to contact the relevant Microsoft team to see whether they can help us document this aspect correctly, considering all the template variants. An other option would be to have the templates use the component to begin with ...

**Comment by hamishwillee** [comment]
Thanks. Template using the component would be a "win", but I do wonder what ratings most of them would get :-0

**Comment by ltomuta** [comment]
:+1:

**Comment by ltomuta** [comment]
I finally got a reply from MSFT, they will consider adding the component as built in. As for individual developers trying to add the component to their AppStudio-generated project, the general guidance applies: main view must be identified (template specific) and then the control is added as the last (top most) component on the page.

I will close this case as no further action is due.

**Comment by Hari-Bonda** [comment]
i am trying to integrate in appstudio generated project i can not do it .... could you please suggest me how to do it or any example projects ...?

**Comment by Hari-Bonda** [comment]
yay i just integrated by fallowing a pdf file :) issue solved i will post video on youtube it will be helpful  further :)

**Comment by ltomuta** [comment]
@haribabubonda Excellent, Yes, please do that:)

**Comment by Hari-Bonda** [comment]
@ltomuta definitely in 2hr i will share youtube link here . i attached a pdf file here i renamed it as .jpg download rename as .pdf.  please add this pdf file to the project 
http://we.tl/Pa1LHhHh9m

**Comment by ltomuta** [comment]
That is indeed this project's documentation and it is already part of the project. It can be found in the Doc folder, as well as in the NuGet package.
