### ISSUE TITLE
FeedbackOverlay behind tekst

### ISSUE THREAD

**Issue by Sjoerdvdn** [microsoft/rate-my-app#31]
FeedBackOverlay is shown behind tekst. 

Location in code:

![ratemyapp 2](https://f.cloud.github.com/assets/6716114/2195558/5b6e676e-98a1-11e3-86cf-c92ced45821e.PNG)

![ratemyapp](https://f.cloud.github.com/assets/6716114/2195546/068c0cf6-98a1-11e3-8510-ee1990586b98.PNG)

**Comment by ltomuta** [comment]
Make sure that the RMA component is places last in the "LayoutRoot" grid.

```
<Grid x:Name="LayoutRoot">

<!-- All your stuff here -->

<rma:FeedbackOverlay ..../></Grid> <!-- LayoutRoot grid ends right after RMA ends -->
```

**Comment by Sjoerdvdn** [comment]
Thanks this solved my problem. Need to read better, found that it was mentioned in the guide.
