### ISSUE TITLE
Rate Message 2 - Italian language typo

### ISSUE THREAD

**Issue by Dani7B** [microsoft/rate-my-app#34]
The message should be:
"Sembra che usi la nostra app un sacco!

Hai pensato a darci 5 stelle per dimostrare il tuo apprezzamento?".
There's a typo in "la nostra" that now is "l anostra". :-)

**Comment by ltomuta** [comment]
Hi Dani,

thanks for reporting this. The strings translation is hosted at http://getlocalization.com/ratemyapp so if you find more such bugs please correct them there.
