### ISSUE TITLE
Allow RMA to be triggered from code behind

### ISSUE THREAD

**Issue by ltomuta** [microsoft/rate-my-app#39]
A proposal is that we allow apps to call RMA whenever it is considered more likely that the user will be inclined to review and give a good score, like right after scoring an achievement of sorts in the game (new level, highest score ... )

To be clarified if this would be something RMA should be used for or rather an option should be given through app's own UI (and RMA will simply execute it, as when triggered from About page)

**Comment by hamishwillee** [comment]
Makes good sense - I'm surprised we don't support it already. Would expect that invoking this way (or through the About) would reset the counter for displaying the rate-me page.

**Comment by ltomuta** [comment]
The advice from the UX expert was that such an option should be implemented in application's own UI so I guess ~~nothing more should be done in RMA to support this feature~~ all we need to do is mention the scenario in documentation.

You are right @hamishwillee, as with the About case the review should be triggered via RMA so that the state of the component is updated accordingly.
