### ISSUE TITLE
FeedbackOverlay properties accessible in code, not just XAML

### ISSUE THREAD

**Issue by Rob-Kachmar** [microsoft/rate-my-app#4]
I may be missing something here, so please correct me if I'm mistaken, but it does not appear that all the customizable properties can be set on the control from code.  It looks like the only way to set certain properties is through XAML.  For instance, the required parameters FeedbackTo, ApplicationName, and CompanyName can only be set through XAML.

I have a use case that would easily be solved with the ability to set values in the code behind.  I have a Spanish translation that I believe is better than the current control.  It would be very simple and convenient to figure out the current user's language, and then override the control's properties only if the source language is Spanish.

```
        string lang = CultureInfo.CurrentUICulture.Name.Substring(0, 2);
        if (lang.Equals("es"))
        {
            // Right now this control does not allow us to set all properties in the code-behind :-(
            //FeedbackOverlay.
        }
```

Now I know I could just change it in the source project, recompile it, and manually add it to my solution, but it's really nice and convenient to just use NuGet and let the authors of the project continue to enhance the control with other translations and functionality instead of having to do my own maintenance to keep up.

Thank you,
Rob

**Comment by hamishwillee** [comment]
Hi Rob
Sounds sensible to me, but will leave to the actual project owners to comment. Whether or not this gets done though, would be good if you could contribute your improved translation: www.getlocalization.com/ratemyapp/
Regards
Hamish

**Comment by ltomuta** [comment]
Hi Rob,

our aim was to enable easy use for the component as is, with minimal code.

You can still override the internal translations if you want, using a value converter, as illustrated below:

``` C#
using RateMyApp.Resources;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Resources;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Data;

namespace PhoneApp2.Converters
{
    public class TranslationOveride : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            string result = string.Empty;

            string lang = culture.Name.Substring(0, 2);
            if (lang.Equals("en"))
            {
                // load your own translation for <parameter> string here
                result = "This is my special string.\nDo you see it?";
            }
            else
            {
                result = RateMyApp.Resources.AppResources.ResourceManager.GetString(parameter.ToString());
            }


            return result;
        }

        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            return string.Empty;
        }
    }
}
```

where the converter is used as follows for overiding for example the translation of RatingMessage1:

``` XML
<phone:PhoneApplicationPage
    <!-- snip -->
    xmlns:converters="clr-namespace:PhoneApp2.Converters"  
    <!-- snip -->
    shell:SystemTray.IsVisible="True">

    <phone:PhoneApplicationPage.Resources>
        <converters:TranslationOveride x:Key="TranslationOverideConverter"/>
    </phone:PhoneApplicationPage.Resources>

    <Grid x:Name="LayoutRoot" Background="Transparent">
    <!-- snip -->
        <ctrl:FeedbackOverlay x:Name="FeedbackOverlay"
                              Grid.RowSpan="2"
                              FeedbackTo="{Binding Path=LocalizedResources.FeedbackTo, Source={StaticResource LocalizedStrings}}"
                              ApplicationName="{Binding Path=LocalizedResources.ApplicationName, Source={StaticResource LocalizedStrings}}"
                              CompanyName="{Binding Path=LocalizedResources.CompanyName, Source={StaticResource LocalizedStrings}}"
                              RatingMessage1="{Binding Source={StaticResource LocalizedStrings}, Converter={StaticResource TranslationOverideConverter}, ConverterParameter=RatingMessage1}"
                              />
    </Grid>

</phone:PhoneApplicationPage>
```

Best regards,
Lucian

**Comment by hamishwillee** [comment]
Hi Lucian

a) is this approach for over-riding strings in a library "standard practice" - ie is it worth having a wiki article on this topic?
b) Can/should we have a section in the guide on this?

regards
H

**Comment by ltomuta** [comment]
a) The use of converters for tweaking bindings or even for creating custom localization solutions (i.e. change the app language on the fly, regardless of system's locales) is pretty old/standard stuff. We could look around in the wiki, see what we have on the topic ([not much](http://developer.nokia.com/search/simple/?s=23&expandDoc=false&oldK=IValueConverter&k=IValueConverter&l=20) it seems) and then maybe add something more.
b) I'd keep it simple, FAQ style, with a link pointing to this issue. As you said above, if good translations are contributed to the project, for all the languages, solutions like these would not be needed frequently anyhow.
